name       : python-dulwich
version    : 0.21.5
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/d/dulwich/dulwich-0.21.5.tar.gz : 70955e4e249ddda6e34a4636b90f74e931e558f993b17c52570fa6144b993103
license    : Apache-2.0
component  : programming.python
summary    : Pure-Python Git implementation
description: |
    This is the Dulwich project. It aims to provide an interface to git repos (both local and remote) that doesn't call out to git directly but instead uses pure Python.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
